In [14]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras import layers
import numpy as np

In [2]:
url='https://raw.githubusercontent.com/redashu/Datasets/master/bank.csv'
dataset=pd.read_csv(url)
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
features=dataset.iloc[:,3:-1].values
label=dataset.iloc[:,-1].values
print(features)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [4]:
le= LabelEncoder() #M(1) & F(0) encoding -- number
features[:,2]=le.fit_transform(features[:,2])
print(features)


[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [8]:
ct1 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
features=np.array(ct1.fit_transform(features))
print(features)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [12]:
trainX,testX,trainY,testY=train_test_split(features,label,train_size=0.2)

In [13]:
# features scaling is a must process for deep learning
sc = StandardScaler()
scaled_trainX=sc.fit_transform(trainX)
print(scaled_trainX)


[[-0.99104014 -0.58889842  1.74601919 ... -1.5202823   0.96946594
  -0.0587643 ]
 [-0.99104014 -0.58889842  1.74601919 ... -1.5202823  -1.03149575
   1.63122115]
 [ 1.00904087 -0.58889842 -0.57273139 ... -1.5202823  -1.03149575
   0.53915236]
 ...
 [-0.99104014  1.69808573 -0.57273139 ...  0.65777257 -1.03149575
  -1.16306361]
 [-0.99104014 -0.58889842  1.74601919 ...  0.65777257  0.96946594
  -1.20040383]
 [ 1.00904087 -0.58889842 -0.57273139 ...  0.65777257 -1.03149575
   1.13343011]]


In [15]:
# creating  ANN model --sequential
myann2=Sequential()


In [16]:
# adding Intermediate / hidden layers
myann2.add(layers.Dense(20,activation='relu')) # first hidden layer
myann2.add(layers.Dense(20,activation='relu'))
myann2.add(layers.Dense(20,activation='relu'))
myann2.add(layers.Dense(1,activation='sigmoid')) # output layer
